### ISSUE TITLE
FusorSV for Species

### ISSUE THREAD

**Issue by jiey6596** [TheJacksonLaboratory/SVE#23]
Can FusorSV merge SV for all the species or just for human?

**Comment by lslochov** [comment]
Hi @jiey6596, FusorSV will work with any species, as the data it works with includes SV type, length, and SV calling software for each structural variant in the input VCFs, and does not depend on the species. It is important, however, that the model file you are using was trained on a ground truth SV callset with the callers that you will use, so that FusorSV knows how to use each caller's data in the merging process. Please let me know if you need any help with this process, or if you have any other questions.

**Comment by jiey6596** [comment]
Thanks for your reply！And I have another question. Can Fsorsv merge SV that recognize from pacbio sequel data with pbsv ,sniffles and any other long reads recognize software.

**Comment by lslochov** [comment]
Since FusorSV will take any VCF, regardless of the software that generated it, it's possible to use long read VCFs in FusorSV. However, we are still working on official support for long reads, and we don't yet know of any particular issues with long reads that we will need to accommodate in FusorSV. Official support is planned in a forthcoming release.
