### ISSUE TITLE
tigra and tigra-ext links dead

### ISSUE THREAD

**Issue by taylorjtamu** [TheJacksonLaboratory/SVE#25]
The tree links under src/ for both tigra and tigra-ext are currently dead. I had existing clones of those repositories so I was able to copy them over manually, but if they're mandatory for building then this should be looked into further.

speedseq has a similar issue with another repository which I've reported to them, but be aware that their dead link makes the git clone --recursive recommended in the installation documentation here fail.

**Comment by lslochov** [comment]
Hi @taylorjtamu , thanks for bringing this to our attention. We will investigate this and push a fix to the dev branch when it's ready.

**Comment by lslochov** [comment]
Dependency repositories won't be checked out if you use a standard `git clone`; you have to use `git clone --recursive`

**Comment by taylorjtamu** [comment]
This was while using a git clone --recursive. It's even in the script I've been working on for a full installation as a git clone --recursive. I'm not sure what's changed, but now the clone is working properly. 
While those dependencies are still dead links, it seems to not matter now. I'll leave it to yall if you want to close this.

**Comment by lslochov** [comment]
On the Github website, it appears that there's no link to a tigra or tigra-ext repository, but I checked the .submodules file, and they're hosted on Bitbucket. Since the other dependencies are hosted on Github, it's possible that Bitbucket repositories aren't automatically hyperlinked. My test of `git clone --recursive`, however, did successfully checkout tigra and tigra-ext, so the main intended functionality is still there.
